### ISSUE TITLE
About loading pre-trained models

### ISSUE THREAD

**Issue by Elliot696** [tanveer-hussain/EfficientSOD2#6]
Hello, I read your paper and want to load the pre-trained model you gave for significance detection on my computer but I am having problems loading the model. Can you teach me the way how to load the model you provided! Thanks a lot!

Traceback (most recent call last):
  File "D:\anaconda\anaconda\envs\wys_bysj\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-e4056a3304e7>", line 1, in <module>
    runfile('E:/wys_bysj/EfficientSOD2/SOD_test.py', wdir='E:/wys_bysj/EfficientSOD2')
  File "C:\Program Files\JetBrains\PyCharm 2019.2.5\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.2.5\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/wys_bysj/EfficientSOD2/SOD_test.py", line 50, in <module>
    model = torch.load('weights/DUT-RGBD_DDNet_Model_500.pt')  # 加载权重文件
  File "D:\anaconda\anaconda\envs\wys_bysj\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\anaconda\anaconda\envs\wys_bysj\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "D:\anaconda\anaconda\envs\wys_bysj\lib\site-packages\torch\serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
  File "C:\Program Files\JetBrains\PyCharm 2019.2.5\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'ModelNetworks'

**Comment by tanveer-hussain** [comment]
You can remove this line, as I didn't see any of these lines in the test.py file.
